sudo: required
services:
  -docker

before_install:
  - docker build -t thyself7771/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thyself7771/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "D+KCourse"
  env: "DKCourse-env"
  bucket_name: "elasticbeanstalk-us-east-1-784005884301"
  bucket_path: "D+KCourse"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"